### ISSUE TITLE
Match color palltes same as the book

### ISSUE THREAD

**Issue by osbc2022** [osbc2022/interactive-eloquent-js-website#7]
Todo :- 
- [ ] match the colors same as the book use 
- [ ] place the colors inside a :root
``` css
:root {
     --primary: #ffd71b;
}
```
